apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tekn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0070-tenant/tkrw-pr712-0075-0070-app/devfile-sample-tekn@sha256:d1cecdf85680e8cd9a593ee41b0d13bbfdfaed06cb1e0cb81184c0118289dfc0
        name: my-nodejs
        resources: {}
status: {}
